### ISSUE TITLE
Bot stuck at ''The item in which we are using is a/an glove case''

### ISSUE THREAD

**Issue by marnixx9** [RobertSkonieczny/node-steam-trade-farm#1]
the bot starts and says ''main client logged in'' ''bot client logged in!'' and than ''The item in which we are using is a/an glove case''

and than it stops doing anything. what do i do?

**Comment by Koncealed** [comment]
Make sure your Shared Secret is correct.

**Comment by 4dams** [comment]
Hey! I didn't want to open an extra issue for this, but you could maybe change the readme to only "npm i" to install all required packages and maybe even add a short note for people having problems adding python to their path on windows 10.

In that case you would have to run `npm --add-python-to-path='true' --debug install --global windows-build-tools`

But really nice project! I really like it! 👍

**Comment by RobertSkonieczny** [comment]
Please see new PR
