### ISSUE TITLE
Change Game

### ISSUE THREAD

**Issue by D3DH4K3R** [RobertSkonieczny/node-steam-trade-farm#10]

**Comment by D3DH4K3R** [comment]
Can i change in the file the game, because c sgo has a 7 day trade ban?
f.ex. to unterned or pubg?

**Comment by Shaxzy** [comment]
Yes

**Comment by Timthetatman** [comment]
yes, go into the config file and change all App IDs to preffered game

**Comment by RobertSkonieczny** [comment]
Please see new PR defaults to TF2
