### ISSUE TITLE
cant install npm sleep

### ISSUE THREAD

**Issue by kakayl616** [RobertSkonieczny/node-steam-trade-farm#11]
![image](https://user-images.githubusercontent.com/65536649/82195901-8dceb880-992b-11ea-9eae-19f71e52ddb7.png)

can someone help me with this? i already installed the 3 commands but it still didnt work :/

**Comment by murathasev** [comment]
Try
`npm install --global node-gyp`

**Comment by RobertSkonieczny** [comment]
Please see new PR
