### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by dz-here** [RobertSkonieczny/node-steam-trade-farm#17]
![Screenshot 2021-04-13 214539](https://user-images.githubusercontent.com/77742040/114597280-a3ff0900-9ca1-11eb-8e4e-3d5d4d2677ec.png)

**Comment by YaZanuda111111** [comment]
There is also a 500 error, but it is related to steam and is not fixed by the bot

**Comment by RobertSkonieczny** [comment]
Can you copy and paste the error here?

**Comment by RobertSkonieczny** [comment]
I found this issue posted on a forum. Just seems like steam is having issues.

https://dev.doctormckay.com/topic/3933-error-http-error-500/
