### ISSUE TITLE
Linux/Debian server?

### ISSUE THREAD

**Issue by GodZeus911** [RobertSkonieczny/node-steam-trade-farm#2]
How to use it in linux/debian server, can i get the setting?

**Comment by 4dams** [comment]
- Download the repository
![image](https://user-images.githubusercontent.com/28960614/34991105-ae67513c-fac8-11e7-8884-13c201363322.png)
- Upload everything to a folder on your server
- Navigate to that folder
- Type `npm i`
- Edit your `config.json`
Aaand run the script via `node bot.js`

**Comment by RobertSkonieczny** [comment]
Please see new PR
