### ISSUE TITLE
Could not accept trade & getting our inventory errors.

### ISSUE THREAD

**Issue by Turquoiseboi** [RobertSkonieczny/node-steam-trade-farm#3]
I just found out 2 issues first one stuck at 'Second Account found an Offer!
Second Account, has accepted trade. Now sending it back.
Could not accept trade.'' after 618 trades..
Second one stuck at ''getting our inventory'' after 30-50 trades...

**Comment by aleko333** [comment]
hello my bot is very slowly can you help me? 5minute=20 Trade :| 
and 150Trades next its crash

**Comment by Turquoiseboi** [comment]
mec gasachirshi var aleko

**Comment by Turquoiseboi** [comment]
zdarova mec igive problema maqvs

**Comment by Turquoiseboi** [comment]
chemtanac egrea

**Comment by masmas15** [comment]
@Turquoiseboi Can you help me with this problem ? error accepting trade https://prnt.sc/qppu4x

**Comment by lunacyxp** [comment]
yeah i have the same problem

**Comment by RobertSkonieczny** [comment]
Please see new PR
