### ISSUE TITLE
Problem with starting the bot.js

### ISSUE THREAD

**Issue by Martinjoo** [RobertSkonieczny/node-steam-trade-farm#6]
1 problem:

Line: 40
Char: 1
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

2 problem:

Line: 66
Char: 28
Error: Syntax error
Code: 800A03EA
Source: Microsoft JScript compilation error

Thanks for helping best regards!

**Comment by RobertSkonieczny** [comment]
Please see new PR
